name: 💾 Daily Backup

on:
  schedule:
    - cron: '0 2 * * *' # Runs at 2 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backup API
        env:
          API_URL: ${{ secrets.BACKUP_API_URL }}
          API_KEY: ${{ secrets.BACKUP_API_KEY }}
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" \
          -X POST $API_URL \
          -H "X-API-KEY: $API_KEY" \
          -H "Content-Type: application/json"

          echo "HTTP Status Code: $response"

          if [ $response -eq 500 ]; then
            echo "Backup failed with a 500 status code"
            cat response.txt
            exit 1
          elif [ $response -ne 200 ]; then
            echo "Unexpected status code: $response"
            cat response.txt
            exit 1
          else
            echo "Backup successful"
            cat response.txt
          fi

      - name: Check Backup Success
        if: failure()
        run: |
          echo "Backup failed. Please check the logs for more information."
          exit 1
